- src/main/java/com/knud4/an/line/entity/Line.java
- src/main/java/com/knud4/an/line/repository/LineRepository.java
- src/test/java/com/knud4/an/repository/LineRepositoryTest.java
Line Entity 에 대해서 생성, 수정, 삭제, 조회 구현
1. 수정, 삭제, 조회 모두 이름에 대해서 열어두었습니다.
2. 전체 조회가 가능하도록 하였습니다.
> FEAT : Line Entity, Repository, Test 추가

- src/main/java/com/knud4/an/line/dto/CreateLineDTO.java
- src/main/java/com/knud4/an/line/dto/FindLineDTO.java
- src/main/java/com/knud4/an/line/dto/UpdateLineDTO.java
- src/main/java/com/knud4/an/line/service/LineService.java
- src/test/java/com/knud4/an/service/LineServiceTest.java
1. Feat: Line Service, DTO 추가하였습니다.
1. Line dto 추가
2. Line Service  추가
3. Line Service Test 추가
1. 계층간의 데이터 객체의 의존성을 줄이기 위해서 dto 를 추가했습니다.
controller: dto 를 생성 및 service layer 로 전달
service: dto 를 바탕으로 dao(entity) 객체 생성
repository: dao 영속화 (주의! service layer 로 영속화 된 객체를 전달하지 않는다.)
로 우선 기준을 정해보았습니다. 의견 부탁드리겠습니다.
> Feat: Line Service, DTO 추가

- src/main/java/com/knud4/an/house/entity/House.java
- src/main/java/com/knud4/an/house/repository/HouseRepository.java
- src/test/java/com/knud4/an/repository/HouseRepositoryTest.java
Local 에 존재하는 Line Entity 참고해서 우선 연관관계 매핑 해놓았고, 해당 부분은 추후에 Line Entity 완성되고 수정될 수 있습니다.
House Entity 생성, 조회, 수정, 삭제 추가했습니다.
Line Entity 와 전체적인 로직은 유사하고
103 동 (라인 이름), 1307호(집 이름) 이 있을 때
1. 103 동 라인의 집 목록을 모두 호출할 수 있습니다.
2. 103 동 1307 호 집 정보를 호출할 수 있습니다.
3. 103 동 1307 호 집 정보를 수정/삭제 할 수 있습니다.
> FEAT : House Entity, Repository, Test 추가

- src/main/java/com/knud4/an/board/Board.java
- src/main/java/com/knud4/an/board/Range.java
1. Feat: Board Entity 추가
1. Feat: Board Entity 추가하였습니다.
1. Member Entity 완성 후에 Member와의 연관관계 설정을 마무리 하겠습니다.
> Feat: Board Entity 추가

- src/main/java/com/knud4/an/utils/jwt/JWTUtil.java
1. JWT Util Class 를 추가했습니다.
1. Secret Key 기반 토큰 생성 및 유효성 검증이 가능합니다
2. Map 기반 으로 payload 를 생성함으로써 확장성 있는 구조를 만들었습니다.
1. Token payload 필드가 정해진 이후에 claim 추출 로직을 추가하겠습니다.
> Feat: JWT Util Class 추가

- src/main/java/com/knud4/an/utils/cookie/CookieUtil.java
Token 을 클라이언트와 주고받을 쿠키를 생성하고, 조회하는 Util class 를 추가합니다.
1. Cookie 를 생성하고 조회할 수 있는 cookie util Class 를 추가했습니다.
1. 쿠키의 생성 (이름, 값)
2. 쿠키의 조회 (서블릿 요청, 이름)
1. 현재 삭제 로직은 포함되어있지 않습니다.
> Feat: Cookie Util Class 추가

- src/main/java/com/knud4/an/account/entity/Account.java
- src/main/java/com/knud4/an/account/entity/Gender.java
- src/main/java/com/knud4/an/account/entity/Profile.java
- src/main/java/com/knud4/an/account/entity/Role.java
- src/main/java/com/knud4/an/account/repository/AccountRepository.java
- src/test/java/com/knud4/an/repository/AccountRepositoryTest.java
1. Account, Profile Entity, Account Repository 추가합니다
1. Account, Profile Entity 추가
2. Account, Profile Repository 추가
1. Profile 의 lifecycle 이 account 에 종속적이기 때문에 하나의 도메인에 포함하였습니다.
> Feat: Account, Profile Entity, Account Repository 추가 

- src/main/java/com/knud4/an/exceptions/NotFoundException.java
- src/main/java/com/knud4/an/line/repository/LineRepository.java
- src/main/java/com/knud4/an/line/service/LineService.java
- src/test/java/com/knud4/an/repository/LineRepositoryTest.java
- src/test/java/com/knud4/an/service/LineServiceTest.java
1. Line Repository, Service 수정 및 NotFoundException 추가
1. Optional 객체 사용에 따른 NotFoundException Class 추가
2. Isuue 사항 Service 및 Reposiotry 에 반영
> Line Repository, Service 수정 및 NotFoundException 추가

- src/main/java/com/knud4/an/house/dto/CreateHouseForm.java
- src/main/java/com/knud4/an/house/entity/House.java
- src/main/java/com/knud4/an/house/repository/HouseRepository.java
- src/main/java/com/knud4/an/house/service/HouseService.java
- src/test/java/com/knud4/an/repository/AccountRepositoryTest.java
- src/test/java/com/knud4/an/repository/HouseRepositoryTest.java
1. [#9] 해당 이슈에 대한 내용을 [#19] 과 함께 제출합니다.
1. issue-19 조건에 맞추어 service layer 설계 및 엔티티 수정
> Feat: House Id 조회 추가, Service 조회 값 수정

- src/main/java/com/knud4/an/account/service/AccountService.java
- src/test/java/com/knud4/an/service/LineServiceTest.java
1. AccountService 추가
1. Account 및 Profile 에 대한 생성/조회 로직 추가
1. [#19] 조건에 맞춰 추가
> Feat: AccountService 추가

- src/main/java/com/knud4/an/comment/entity/Comment.java
- src/main/java/com/knud4/an/comment/repository/CommentRepository.java
1. Comment Entity, Repository 추가합니다.
1. Comment Entity 추가
2. Comment Repository 추가
1. Community 구현 후 연관관계 설정 및 Community id로 조회 기능 추가 예정입니다.
> Feat/issue 3/comment entity

- src/main/java/com/knud4/an/account/repository/AccountRepository.java
- src/main/java/com/knud4/an/auth/controller/AuthController.java
- src/main/java/com/knud4/an/auth/dto/profile/AddProfileForm.java
- src/main/java/com/knud4/an/auth/dto/profile/SignInProfileForm.java
- src/main/java/com/knud4/an/auth/service/AuthService.java
- src/main/java/com/knud4/an/exception/GlobalExceptionHandler.java
- src/main/java/com/knud4/an/security/filter/JwtAuthenticationFilter.java
- src/main/java/com/knud4/an/security/provider/JwtProvider.java
1. Account 검증 로직 일부 수정 및 Auth Controller 를 추가합니다
1. profile 이름 중복 검증 로직을 추가합니다.
2. boolean 타입을 반환하는 메소드를 삭제하고 예외를 발생시키는 방식으로 변경하였습니다.
3. 회원가입, 로그인, 프로필 추가, 프로필 로그인 api 를 추가합니다
> Account 검증 로직 일부 수정 및 Auth Controller 추가

- src/main/java/com/knud4/an/house/repository/HouseRepository.java
- src/main/java/com/knud4/an/house/service/HouseService.java
- src/main/java/com/knud4/an/line/repository/LineRepository.java
- src/main/java/com/knud4/an/line/service/LineService.java
1. 라인, 세대명 중복 검증 로직 추가
1. 라인, 세대명 중복 검증 로직 추가
1.
> Refactor: 라인, 세대명 중복 검증 로직 추가

- src/main/java/com/knud4/an/house/controller/HouseController.java
- src/main/java/com/knud4/an/house/dto/HouseDTO.java
- src/main/java/com/knud4/an/house/dto/HouseListResponse.java
1. HouseController 및 DTO 추가합니다.
1. 라인 생성, 목록 조회 api 추가
1.
> Feat: HouseController 및 DTO 추가

- src/main/java/com/knud4/an/line/controller/LineController.java
- src/main/java/com/knud4/an/line/dto/CreateLineResponse.java
- src/main/java/com/knud4/an/line/dto/LineDTO.java
- src/main/java/com/knud4/an/line/dto/LineListDTO.java
1. LineController 및 DTO 추가합니다.
1. 라인 생성, 목록 조회 api 추가
1.
> Feat: LineController 및 DTO 추가

- src/main/java/com/knud4/an/community/entity/Category.java
- src/main/java/com/knud4/an/community/entity/Community.java
- src/main/java/com/knud4/an/community/repository/CommunityRepository.java
1. Community Entity, Repository 추가합니다.
1. Community Entity 추가
2. Community Repository 추가
1. Comment와의 연관관계 설정 예정입니다.
> Feat/issue 3/community entity

- src/main/java/com/knud4/an/board/Board.java
- src/main/java/com/knud4/an/comment/entity/Comment.java
- src/main/java/com/knud4/an/community/entity/Community.java
- src/main/java/com/knud4/an/notice/entity/Notice.java
1. Board, Comment, Community, Notice 클래스에 생성자 추가
1. Board 클래스에 생성자 추가합니다.
2. Community 클래스에 생성자 추가합니다.
3. Comment 클래스에 생성자 추가합니다.
4. Notice 클래스에 생성자 추가합니다.
1. @Builder 사용했습니다.
> Feat: Board, Comment, Community, Notice 클래스에 생성자 추가

- src/main/java/com/knud4/an/account/controller/AccountController.java
- src/main/java/com/knud4/an/account/dto/ProfileDTO.java
- src/main/java/com/knud4/an/account/dto/ProfileListResponse.java
1. Account Controller 추가하였습니다.
1. 프로필 목록 조회 추가
2. 내 프로필 조회 추가
1.
> Feat: Account Controller 추가

- src/main/java/com/knud4/an/auth/controller/AuthController.java
- src/main/java/com/knud4/an/config/SecurityConfigure.java
- src/main/java/com/knud4/an/config/WebConfig.java
- src/main/java/com/knud4/an/exception/handler/JwtAccessDeniedHandler.java
- src/main/java/com/knud4/an/exception/handler/JwtNotAuthenticatedHandler.java
- src/main/java/com/knud4/an/interceptor/AccountTokenInterceptor.java
- src/main/java/com/knud4/an/interceptor/ProfileTokenInterceptor.java
- src/main/java/com/knud4/an/utils/cookie/CookieUtil.java
1. Https 추가에 따른 쿠키, config 로직 일부 수정
2. Interceptor 이슈 해결
1. Cookie -> ResponseCookie 클래스 변경
2. webMvcConfig 를 https 통신에 맞게 수정
3. Interceptor 에서 예외 발생 시 Controller 로 요청 위임
1.
> Https 추가에 따른 쿠키, config 로직 일부 수정 / Interceptor 이슈 해결

- src/main/java/com/knud4/an/comment/repository/CommunityCommentRepository.java
- src/main/java/com/knud4/an/comment/repository/ReportCommentRepository.java
1. CommunityComment, ReportComment Repository 추가합니다.
1. CommunityComment Repository 추가
2. ReportComment Repository 추가
1. 저장, community_id 또는 report_id로 페이징 조회, 댓글 수 조회를 추가합니다.
> Feat: Comment Repository 추가

- src/main/java/com/knud4/an/comment/entity/ReportComment.java
- src/main/java/com/knud4/an/report/entity/Report.java
1. Report 연관관계 수정, 편의 메소드 수정
1. Report 의 Comment 연관관계를 삭제합니다.
2. Report 생성 시 House, Line 정보를 함께 저장합니다.
1.
> Refactor: Report 연관관계 수정, 편의 메소드 수정

- src/main/java/com/knud4/an/community/dto/CreateCommunityForm.java
- src/main/java/com/knud4/an/community/repository/CommunityRepository.java
- src/main/java/com/knud4/an/community/service/CommunityService.java
- src/test/java/com/knud4/an/repository/CommunityRepositoryTest.java
1. Community Repository 테스트, 수정 및 Service 추가합니다.
1. Community Repository 모든 목록 조회 함수에 페이징, 내림차순 적용
2. Community Repository에 공개범위로 검색 추가
3. Community Service 추가
1. 기간 별 커뮤니티 글 조회 서비스 구현 전입니다.
> Feat: Community Repository 테스트, 수정 및 Service 추가

- build.gradle
- src/main/java/com/knud4/an/AnApplication.java
- src/main/java/com/knud4/an/config/RedisConfig.java
- src/main/java/com/knud4/an/utils/redis/RedisUtil.java
1. Spring Redis 를 추가합니다.
1. Spring data Redis 의존성 추가
2. RedisConfig 추가
- LettuceConnectionFactory 추가  (Connection 관리)
- RedisTemplate 추가 (Redis Method 구현)
3. RedisUtil  추가 (set, get, expire, del)
1.
> Feat: Redis 추가

- src/main/java/com/knud4/an/board/Board.java
- src/main/java/com/knud4/an/board/Range.java
- src/main/java/com/knud4/an/community/dto/CreateCommunityForm.java
- src/main/java/com/knud4/an/community/entity/Community.java
- src/main/java/com/knud4/an/community/entity/Range.java
- src/main/java/com/knud4/an/community/repository/CommunityRepository.java
- src/main/java/com/knud4/an/community/service/CommunityService.java
- src/main/java/com/knud4/an/notice/dto/CreateNoticeForm.java
- src/main/java/com/knud4/an/notice/entity/Notice.java
- src/main/java/com/knud4/an/notice/repository/NoticeRepository.java
- src/main/java/com/knud4/an/notice/service/NoticeService.java
1. Notice Repository 수정 및 Service 추가합니다.
1. Notice Repository 공개범위로 조회 추가
2. Notice와 Line 간 연관관계 삭제 및 releaseLine 타입 변경
3. Notice Service 추가
1. 기간 별 조회는 구현 전입니다.
> Feat: Notice Repository 수정 및 Service 추가

- src/main/java/com/knud4/an/notice/controller/NoticeController.java
- src/main/java/com/knud4/an/notice/dto/NoticeDTO.java
- src/main/java/com/knud4/an/notice/service/NoticeService.java
1. Notice DTO, Controller 추가합니다.
1. Notice Service에서 공지글 생성 시 역할 검사 삭제
2. Notice DTO 추가
3. Notice Controller 추가
1. 공지사항 작성자 데이터 논의 후 추가 예정입니다.
> Feat: Notice DTO, Controller 추가

- src/main/java/com/knud4/an/auth/controller/AuthController.java
- src/main/java/com/knud4/an/auth/service/AuthService.java
- src/main/java/com/knud4/an/smtp/controller/AuthMailController.java
- src/main/java/com/knud4/an/smtp/service/AuthMailService.java
1. AuthMailController 추가하였습니다.
2. AuthController 메일 인증 기능 추가하였습니다.
1. AuthMailController: 인증 코드 전송, 재전송 로직 추가
2. AuthController: 코드 인증 로직 및 인증된 메일의 회원 가입만을 허용하도록 변경
1.
> Feat: AuthMailController 추가 + Auth 메일 인증 기능 추가

- src/main/java/com/knud4/an/comment/dto/CreateCommentForm.java
- src/main/java/com/knud4/an/comment/repository/CommunityCommentRepository.java
- src/main/java/com/knud4/an/comment/repository/ReportCommentRepository.java
- src/main/java/com/knud4/an/comment/service/CommunityCommentService.java
- src/main/java/com/knud4/an/comment/service/ReportCommentService.java
1. CommunityComment, ReportComment Service 추가합니다.
1. CommunityComment Repository의 findCountByCommunityId를 findCommentCountByCommunityId로 변경
2. ReportComment Repository의 findCountByReportId를 findCommentCountByReportId로 변경
3. CreateCommentForm 추가
4. CommunityComment Service, ReportComment Service 추가
> Feat: CommunityComment, ReportComment Service 추가

- src/main/java/com/knud4/an/community/controller/CommunityController.java
- src/main/java/com/knud4/an/community/dto/CommunityDTO.java
- src/main/java/com/knud4/an/community/service/CommunityService.java
1. Community DTO, Controller 추가합니다.
1. Community Service의 전체 조회 기능에서 관리자 권한 추가
2. Community DTO 추가
3. Community Controller 추가
1. 댓글 수 전달은 일단 보류했습니다.
4. 테스트 전입니다.
> Feat: Community DTO, Controller 추가

- src/main/java/com/knud4/an/comment/controller/CommentController.java
- src/main/java/com/knud4/an/comment/dto/CommentDTO.java
1. Comment Controller, DTO 추가합니다.
1. Comment Controller 추가
2. Comment DTO 추가
1. CommunityComment와 ReportComment를 공용으로 사용할 수 있도록 구현했습니다.
> Feat: Comment Controller, DTO 추가

- src/main/java/com/knud4/an/config/RedisConfig.java
1. 원격 서버 https 적용 및 Redis-Spring Container 연결을 하였습니다.
1. certbot 을 이용한 letsencrypt CA 인증서 발급 및 원격 서버 적용 (테스트 완료)
2. 원격 서버에 Redis 를 추가하면서 container network 공유가 필요 -> docker 가상 네트워크 생성(an-bridge) 후에 두 컨테이너 연결 완료
1.
> Refactor: https 적용, Redis-Spring Container network 연결

- src/main/java/com/knud4/an/account/controller/AccountController.java
- src/main/java/com/knud4/an/auth/controller/AuthController.java
- src/main/java/com/knud4/an/auth/dto/codeVerificationDTO.java
- src/main/java/com/knud4/an/config/SecurityConfigure.java
- src/main/java/com/knud4/an/config/WebConfig.java
- src/main/java/com/knud4/an/exception/handler/GlobalExceptionHandler.java
- src/main/java/com/knud4/an/house/controller/HouseController.java
- src/main/java/com/knud4/an/line/controller/LineController.java
- src/main/java/com/knud4/an/report/controller/ReportController.java
- src/main/java/com/knud4/an/smtp/controller/AuthMailController.java
1. api 경로를 수정합니다.
1. api 경로 복수형 수정
2. api 경로 패턴 수정
경로 패턴
/api/v1/auth/profiles/**: auth 서비스 중 account token 을 통한 인증 필요
/api/v1/accounts/**: account 서비스 중 account token 을 통한 인증 필요
/api/v1/reports/**: report 서비스 중 account token 을 통한 인증 필요
/api/v1/profiles/**: profile(accout) 서비스 중 profile token 을 통한 인증 필요
> Refactor: api 경로 변경

- build.gradle
- src/main/java/com/knud4/an/exception/handler/GlobalExceptionHandler.java
- src/main/java/com/knud4/an/logger/LoggingFilter.java
- src/main/java/com/knud4/an/logger/RequestWrapper.java
- src/main/java/com/knud4/an/logger/ResponseWrapper.java
1.  logger 를 추가합니다.
1. request parameter, body 로깅 추가
2. response status, body 로깅 추가
3. 예외 발생 시 stacktrace 로깅 추가
1.
> Feat: logger 추가

- src/main/java/com/knud4/an/auth/controller/AuthController.java
- src/main/java/com/knud4/an/config/SecurityConfig.java
- src/main/java/com/knud4/an/config/SwaggerConfig.java
1. 계정/프로필 로그아웃 기능 추가,  swagger configure 추가, Manager 접근 권한 수정하였습니다.
1. 계정/프로필 로그아웃 api 추가하였습니다.
2. swagger custom configure 추가 (Authorization Header 추가 가능)
3. Manager 접근 권한을 수정합니다. (매니저 -> Security JWTAccountFilter 검증)
1.
> 계정/프로필 로그아웃 기능 추가,  swagger configure 추가, Manager 접근 권한 수정

- src/main/java/com/knud4/an/community/controller/CommunityController.java
- src/main/java/com/knud4/an/community/dto/CommunityListDTO.java
- src/main/java/com/knud4/an/community/repository/CommunityRepository.java
- src/main/java/com/knud4/an/community/service/CommunityService.java
1. CommunityListDTO 추가합니다.
1. 오탈자 수정
2. CommunityListDTO 추가 (isLastPage 추가)
1. 커뮤니티글 목록 조회 시 마지막 페이지인지 표시 요청이 있어 추가했습니다.
> Feat: CommunityListDTO 추가

- src/main/java/com/knud4/an/comment/controller/CommentController.java
- src/main/java/com/knud4/an/comment/repository/CommunityCommentRepository.java
- src/main/java/com/knud4/an/comment/repository/ReportCommentRepository.java
- src/main/java/com/knud4/an/comment/service/CommunityCommentService.java
- src/main/java/com/knud4/an/comment/service/ReportCommentService.java
1. Comment 삭제 기능 추가합니다.
1. findOne을 findById:Optional<>로 수정
2. 댓글 id로 1개 삭제 기능 추가
3. 게시글 id로 전체 댓글 삭제 기능 추가
1. 악플 대응으로 댓글 수정 기능은 구현하지 않습니다.
2. 삭제된 댓글 백업 및 관리는 추후 추가 예정입니다.
> Feat: Comment 삭제 기능 추가

- build.gradle
- src/main/java/com/knud4/an/config/StompWebSocketConfig.java
- src/main/java/com/knud4/an/logger/LoggingFilter.java
- src/main/java/com/knud4/an/security/provider/JwtProvider.java
- src/main/java/com/knud4/an/websocket/controller/AlertController.java
- src/main/java/com/knud4/an/websocket/dto/MessageDTO.java
- src/main/java/com/knud4/an/websocket/handler/StompErrorHandler.java
- src/main/java/com/knud4/an/websocket/interceptor/StompInboundInterceptor.java
- src/main/java/com/knud4/an/websocket/interceptor/StompInterceptor.java
1. WebSocket, Stomp (Messaging Protocol) 추가
1. gradle.build 파일 정리, 토큰 만료기간 오타 수정, ip logging 추가
2. WebSocket 추가
3. Message Broker 추가(SimpleBroker제공)
1. 구체적인 연결 방법은 협업 문서에 기재하겠습니다.
> Feat: WebSocket, Stomp 추가

- src/main/java/com/knud4/an/comment/controller/CommentController.java
- src/main/java/com/knud4/an/comment/dto/CommentDTO.java
- src/main/java/com/knud4/an/comment/dto/CommentListDTO.java
- src/main/java/com/knud4/an/comment/service/CommunityCommentService.java
- src/main/java/com/knud4/an/comment/service/ReportCommentService.java
1. Comment api response 데이터 수정합니다.
1. CommentListDTO 추가
2. CommentDTO에 Writer 객체, id, createdDate 추가
1. 함수 이름 정리 필요합니다.
> Feat: Comment api response 데이터 수정

- src/main/java/com/knud4/an/config/StompWebSocketConfig.java
- src/main/java/com/knud4/an/exception/IllegalMessagingException.java
- src/main/java/com/knud4/an/exception/handler/GlobalExceptionHandler.java
- src/main/java/com/knud4/an/websocket/controller/AlertController.java
- src/main/java/com/knud4/an/websocket/dto/AcceptDTO.java
- src/main/java/com/knud4/an/websocket/interceptor/StompInboundInterceptor.java
1. 1:1 Messaging Queue 추가, 비상 알림 수락 추가
1. 1:1 Messaging Queue 구독 경로 추가 (에러 사항 알림)
2. 비상 알림 수락
1.
> Feat: 1:1 Messaging Queue 추가, 비상 알림 수락 추가

- src/main/java/com/knud4/an/security/details/ProfileDetailsService.java
- src/main/java/com/knud4/an/security/filter/JwtProfileAuthenticationFilter.java
- src/main/java/com/knud4/an/security/provider/JwtProvider.java
1. Fix: JwtProfile Filter 에 profile 검증 로직 추가
1. 기존 AccountDetailService 에서 Profile 검증 로직을 추가한 ProfileDetailService 를 추가합니다.
1.
> Fix: JwtProfile Filter 에 profile 검증 로직 추가

- src/main/java/com/knud4/an/report/controller/ReportController.java
- src/main/java/com/knud4/an/report/dto/ReportDTO.java
- src/main/java/com/knud4/an/report/dto/ReportListDTO.java
- src/main/java/com/knud4/an/report/repository/ReportRepository.java
- src/main/java/com/knud4/an/report/service/ReportService.java
1. 클라이언트 요구사항대로 Report 응답 로직을 수정하였습니다.
1. 응답 로직 형태 수정
2. 요청 범위 체크 로직 추가
1. inner class 는 외부 참조의 메모리 누수 때문에 모두 static 메소드로 선언합니다.
> Refactor: Report List 응답 로직 수정

- src/main/java/com/knud4/an/account/controller/AccountController.java
- src/main/java/com/knud4/an/account/dto/ProfileDTO.java
- src/main/java/com/knud4/an/account/dto/ProfileListResponse.java
- src/main/java/com/knud4/an/account/entity/Account.java
- src/main/java/com/knud4/an/account/entity/Profile.java
- src/main/java/com/knud4/an/report/dto/ReportDTO.java
1. 민원 조회 응답 데이터에 Writer id 를 추가하였습니다.
1. 민원 조회 응답 데이터 수정
1.
> Refactor: 민원 조회 응답 데이터에 Writer id 추가

- src/main/java/com/knud4/an/auth/controller/AuthController.java
- src/main/java/com/knud4/an/auth/dto/manager/SignInManagerResponse.java
- src/main/java/com/knud4/an/auth/service/AuthService.java
1. Manager Login 추가
1. Manager Login 시 계정, 프로필 토큰 동시 발급
1.
> Feat: Manager Login 추가

- src/main/java/com/knud4/an/account/controller/AccountController.java
- src/main/java/com/knud4/an/account/dto/ProfileDTO.java
- src/main/java/com/knud4/an/account/entity/Account.java
1.  Account Entity 에서 line, house 정보 저장
1. API 응답 로직 수정 및 효율적인 데이터 제공을 위해 Entity 일부 수정
1.
> Refactor: Account Entity 에서 line, house 정보 저장

- src/main/java/com/knud4/an/comment/service/CommunityCommentService.java
- src/main/java/com/knud4/an/comment/service/ReportCommentService.java
- src/main/java/com/knud4/an/community/service/CommunityService.java
- src/main/java/com/knud4/an/notice/service/NoticeService.java
1. Community, Notice, Comment isLastPage, isFirstPage 오류 수정합니다.
1. Community, Notice, Comment isLastPage, isFirstPage 오류 수정
2. Community, Notice, Comment validatePaging 추가
1.
> Fix: Community, Notice, Comment isLastPage, isFirstPage 오류 수정

- src/main/java/com/knud4/an/comment/controller/CommentController.java
- src/main/java/com/knud4/an/comment/dto/CommentDTO.java
- src/main/java/com/knud4/an/community/service/CommunityService.java
1. Community 라인 게시물 목록 수정합니다.
2. Comment 응답 로직 수정합니다.
1. Community 라인 게시물 목록 라인 공개 게시글만 보이게 수정
2. Comment 응답 로직 isMine 추가 
1.
> Feat:  Community 오류 수정 및 Comment 응답 로직 수정

- src/main/java/com/knud4/an/community/service/CommunityService.java
- src/main/java/com/knud4/an/notice/service/NoticeService.java
- src/main/java/com/knud4/an/report/service/ReportService.java
1. 모든 게시글 상세 조회 관리자 접근 권한 추가
1. Community 상세 조회 관리자 접근 권한 추가
2. Notice 상세 조회 관리자 접근 권한 추가 
3. Report 상세 조회 관리자 접근 권한 추가
1.
> Fix: 모든 게시글 상세 조회 관리자 접근 권한 추가

- src/main/java/com/knud4/an/comment/dto/CommentDTO.java
1. Comment 응답 로직에 writerId 추가합니다.
1. CommentDTO의 Writer inner class에 id 필드 추가
1.
> Feat: Comment 응답 로직에 writerId 추가

- src/main/java/com/knud4/an/config/SecurityConfig.java
1. security 관리자 프로필 권한 추가합니다.
1. security단에서 관리자도 프로필 권한을 가지도록 추가
1.
> Fix: security 관리자 프로필 권한 추가

- src/main/java/com/knud4/an/config/SecurityConfig.java
- src/main/java/com/knud4/an/exception/TokenNotFoundException.java
- src/main/java/com/knud4/an/security/filter/JwtAuthenticationFilter.java
- src/main/java/com/knud4/an/security/filter/JwtExceptionFilter.java
- src/main/java/com/knud4/an/security/filter/JwtProfileAuthenticationFilter.java
- src/main/java/com/knud4/an/utils/jwt/JwtExtractor.java
1. JwtExceptionFilter - JwtAuthentication 로 이어지는 로직을 추가했습니다.
1. JwtExceptionFilter 를 추가했습니다.
1.
> Feat: Jwt 관련 예외 핸들링 필터 추가

- src/main/java/com/knud4/an/account/repository/AccountRepository.java
- src/main/java/com/knud4/an/account/service/AccountService.java
- src/main/java/com/knud4/an/community/service/CommunityService.java
- src/main/java/com/knud4/an/exception/handler/GlobalExceptionHandler.java
- src/main/java/com/knud4/an/security/details/ProfileDetailsService.java
1. EntityManager 의 find 메소드에서 null 리턴 시 Optional 반환 로직으로 변경하였습니다
> Refactor: em.find -> Optional 반환 로직으로 변경

- src/main/java/com/knud4/an/account/repository/AccountRepository.java
- src/main/java/com/knud4/an/account/service/AccountService.java
- src/main/java/com/knud4/an/community/controller/CommunityController.java
- src/main/java/com/knud4/an/community/repository/CommunityRepository.java
- src/main/java/com/knud4/an/community/service/CommunityService.java
- src/main/java/com/knud4/an/notice/controller/NoticeController.java
- src/main/java/com/knud4/an/notice/repository/NoticeRepository.java
- src/main/java/com/knud4/an/notice/service/NoticeService.java
- src/main/java/com/knud4/an/report/service/ReportService.java
- src/main/java/com/knud4/an/security/details/ProfileDetailsService.java
- src/main/java/com/knud4/an/websocket/interceptor/StompInboundInterceptor.java
1. Community, Notice 목록 조회 로직 수정합니다.
1. 기존 controller 및 service단에서 조건문으로 repository 메서드 호출 -> query에서 where문으로 처리
1. 기존 로직에서 페이징 이슈가 있어 수정합니다.
> Fix: Community, Notice 목록 조회 로직 변경

- src/main/java/com/knud4/an/exception/CookieNotFoundException.java
- src/main/java/com/knud4/an/logger/LoggingFilter.java
- src/main/java/com/knud4/an/security/filter/JwtExceptionFilter.java
- src/main/java/com/knud4/an/utils/cookie/CookieUtil.java
1. 불필요한 로깅 로직을 수정하였습니다.
1. 더 이상 토큰 재발급 요청/응답을 로깅하지 않습니다.
2. 더 이상 쿠키를 찾을 수 없는 예외를 로깅하지 않습니다.
1.
> Refactor: 로깅 로직 수정

- src/main/java/com/knud4/an/account/entity/Account.java
- src/main/java/com/knud4/an/account/entity/Profile.java
- src/main/java/com/knud4/an/base/BaseEntity.java
- src/main/java/com/knud4/an/base/BaseTimeEntity.java
- src/main/java/com/knud4/an/board/Board.java
- src/main/java/com/knud4/an/comment/entity/Comment.java
- src/main/java/com/knud4/an/community/controller/CommunityController.java
- src/main/java/com/knud4/an/community/repository/CommunityRepository.java
- src/main/java/com/knud4/an/community/service/CommunityService.java
- src/main/java/com/knud4/an/line/entity/Line.java
- src/main/java/com/knud4/an/notice/controller/NoticeController.java
- src/main/java/com/knud4/an/notice/repository/NoticeRepository.java
- src/main/java/com/knud4/an/notice/service/NoticeService.java
- src/main/java/com/knud4/an/report/controller/ReportController.java
- src/main/java/com/knud4/an/report/entity/Report.java
- src/main/java/com/knud4/an/report/repository/ReportRepository.java
- src/main/java/com/knud4/an/report/service/ReportService.java
1. Community, Report, Notice 목록 오류 수정합니다.
1. Community, Report, Notice 목록 counting 로직 추가
2. isLastPage 수정
3. validatePaging 수정
1.
> Fix: Community, Report, Notice 목록 오류 수정

- src/main/java/com/knud4/an/auth/service/AuthService.java
1. Feat: Password Validator 를 추가하였습니다.
1. 
1.
> Feat: Password Validator

- src/main/java/com/knud4/an/account/dto/ProfileDTO.java
- src/main/java/com/knud4/an/account/entity/Profile.java
- src/main/java/com/knud4/an/account/repository/AccountRepository.java
- src/main/java/com/knud4/an/auth/service/AuthService.java
1. Profile에 idx 필드 추가 및 응답 로직 수정합니다.
1. Profile Entity 및 dto에 idx 필드 추가
2. Profile Repository에 해당 계정 내 프로필 개수 조회 메서드 추가
3. Profile 추가 서비스에 idx 설정 로직 추가
1.
> Feat: Profile에 idx 필드 추가 및 응답 로직 수정

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- README.md
1. 오픈 소스 프로젝트 관련 문서 추가
1. MIT License 추가
2. Contributing.md 추가
3. Code_of_conduct 추가
4. README 해당 내용 추가
1.
> 오픈 소스 프로젝트 관련 문서 추가

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- README.md
> 오픈소스 파일 재 추가

- build.gradle
- src/main/java/com/knud4/an/account/dto/ProfileDTO.java
- src/main/java/com/knud4/an/account/entity/Profile.java
- src/main/java/com/knud4/an/auth/controller/AuthController.java
- src/main/java/com/knud4/an/auth/dto/profile/AddProfileForm.java
- src/main/java/com/knud4/an/auth/service/AuthService.java
- src/main/java/com/knud4/an/gcp/storage/service/FileService.java
- src/main/java/com/knud4/an/logger/LoggingFilter.java
- src/main/java/com/knud4/an/security/provider/JwtProvider.java
1. GCP Storage 연결
2. 프로필 업로드 로직 추가
1. 프로필 이미지 필드 추가
2. 프로필 정보 응답 스펙 변경
3. GCP Storage 의존성 및 서비스 로직 추가
1.
> 프로필 업로드 기능 추가

- src/main/java/com/knud4/an/account/controller/AccountController.java
- src/main/java/com/knud4/an/account/dto/AccountDTO.java
1. 계정 정보 조회 로직 추가
1. account token 을 통한 계정 정보 조회 로직 추가
1.
> Feat: 계정 정보 조회 로직 추가

- src/main/java/com/knud4/an/websocket/controller/AlertController.java
- src/main/java/com/knud4/an/websocket/dto/MessageDTO.java
1. Refactor: WebSocket 요청에 사용자 위치정보 포함
1.
1.
> Refactor: WebSocket 요청에 사용자 위치정보 포함
